pipeline {
    agent any

    stages {
        stage('Lint') {
            steps {
                sshagent(['lab6a']) {
                    sh 'ssh lab6a "pylint --fail-under 5 audit_log/*.py"'
                }
            }
        }
        stage('Security') {
            steps {
                sshagent(['lab6a']) {
                    sh 'ssh lab6a "docker login -u zafyyre -p \'$TOKEN\' docker.io"'
                    sh 'ssh lab6a "docker build -t audit_log:latest ."'
                    sh 'ssh lab6a "trivy image --exit-code 1 --severity HIGH,CRITICAL audit_log:latest"'
                }
            }
        }
        stage('Package') {
            steps {
                sshagent(['lab6a']) {
                    sh 'ssh lab6a "docker login -u zafyyre -p \'$TOKEN\' docker.io"'
                    sh 'ssh lab6a "docker build -t audit_log:latest ."'
                    sh 'ssh lab6a "docker push zafyyre/audit_log:latest"'
                }
            }
        }
        stage('Deploy') {
            steps {
                sshagent(['lab6a']) {
                    sh 'ssh lab6a "docker pull zafyyre/audit_log:latest && docker-compose -f deployment/docker-compose.yml up -d"'
                }
            }
        }
    }
}
