pipeline {
    agent any

    // This stage is for checking out the code from your GitHub repository
    stages {
        stage('Lint') {
            steps {
                sh "pylint --fail-under 5 audit_log/*.py"
            }
        }

        stage('Security') {
            steps {
                sh 'pip3 install bandit'
                sh 'bandit -r audit_log/ -lll -iii'
            }
        }

        stage('Package') {
            steps {
                withCredentials([string(credentialsId: 'DockerHub', variable: 'TOKEN')]) {
                    sh "docker login -u zafyyre -p '$TOKEN' docker.io"
                    sh "docker build -t audit_log:latest audit_log/."
                    sh "docker push zafyyre/audit_log:latest"
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['lab6a']) {
                    withCredentials([string(credentialsId: 'DockerHub', variable: 'TOKEN')]) {
                        sh "docker login -u zafyyre -p '$TOKEN' docker.io"
                        sh "docker pull zafyyre/audit_log:latest"
                        sh "docker-compose -f deployment/docker-compose.yml up -d"
                    }
                }
            }
        }
    }
}
